spring:
  application:
    name: 'blogprj'
  datasource:
    url: jdbc:mysql://localhost:3308/blogdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      properties:
        hibernate:
          show-sql: true
          format-sql: true
      hibernate:
        ddl-auto: create
